SEED_VENTURES = [
    {"name": "Desktop Metal", "website": "https://www.desktopmetal.com", "description": "Mass production metal 3D printing systems for manufacturing"},
    {"name": "Velo3D", "website": "https://www.velo3d.com", "description": "Advanced metal additive manufacturing without support structures"},
    {"name": "Dandelion Energy", "website": "https://dandelionenergy.com", "description": "Residential geothermal heating and cooling systems"},
    {"name": "Miso Robotics", "website": "https://misorobotics.com", "description": "AI-powered robotic kitchen assistants for food service"},
    {"name": "Gecko Robotics", "website": "https://www.geckorobotics.com", "description": "Wall-climbing robots for industrial infrastructure inspection"},
    {"name": "Bright Machines", "website": "https://www.brightmachines.com", "description": "Software-defined factory automation and intelligent assembly"},
    {"name": "Relativity Space", "website": "https://www.relativityspace.com", "description": "3D-printed rockets and autonomous rocket factory"},
    {"name": "Redwood Materials", "website": "https://www.redwoodmaterials.com", "description": "Battery recycling and circular supply chain for materials"},
    {"name": "Turntide Technologies", "website": "https://turntide.com", "description": "Smart electric motor systems for buildings and vehicles"},
    {"name": "Nauticus Robotics", "website": "https://www.nauticusrobotics.com", "description": "Autonomous ocean robots for subsea inspection and maintenance"},
    {"name": "Arch Systems", "website": "https://www.archsys.io", "description": "Manufacturing data analytics and industrial IoT platform"},
    {"name": "Nuvve", "website": "https://nuvve.com", "description": "Vehicle-to-grid (V2G) technology for energy management"},
    {"name": "Ecozen Solutions", "website": "https://www.ecozensolutions.com", "description": "Solar-powered cold storage and irrigation for agriculture (ASME ISHOW alumni)"},
    {"name": "Kheyti", "website": "https://www.kheyti.com", "description": "Greenhouse-in-a-box for smallholder farmers (ASME ISHOW alumni)"},
]
